{{- with .Values.serviceAccount -}}
{{- if .createNew }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | quote }}
  labels:
{{ include "sharedlabels" $ | indent 4 }}
{{- if .annotations }}
  annotations:
{{- toYaml .annotations | nindent 4 }}
{{- end }}
{{- end }}
{{- end -}}
